- name: Generate join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['k8s-masters'][0] }}"

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- name: Run kubeadm join
  shell: "{{ kubeadm_join }}"

- pause:
    prompt: "Wait for containers to Pull and install"