
- name: copy local-storage-provisioner manifests
  template:
    src: local-storage-provisioner.yaml
    dest: /tmp/local-storage-provisioner.yaml
    force: yes

- name: Create Local Storage Provisioner Deployments
  shell: kubectl apply -f /tmp/local-storage-provisioner.yaml