- name: Docker Pull Container Images
  shell: docker pull {{ tiller_image }}
  delegate_to: "{{ item }}"
  with_items: "{{ groups['k8s-workers'] }}"

- name: Helm download and install
  shell: export HELM_URL=https://storage.googleapis.com/kubernetes-helm/helm-v2.12.1-$(uname | tr A-Z a-z)-amd64.tar.gz && curl "$HELM_URL" | tar --strip-components 1 -C /usr/local/bin -zxf -
  environment: "{{proxy_env}}"

- name: Create Helm namespace
  shell: kubectl create ns kube-tiller

- name: Create Helm service-account
  shell: kubectl create serviceaccount tiller --namespace kube-tiller

- name: Create Helm ClusterRoleBinding
  shell: 
    cmd: |
      cat << EOF | kubectl create -f -
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: tiller
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: tiller
          namespace: kube-tiller
      EOF

- name: Helm init
  shell: /usr/local/bin/helm init --service-account tiller --tiller-namespace kube-tiller 
  environment: "{{proxy_env}}"
