- name: Docker Pull Kafka Container Images
  shell: docker pull confluentinc/cp-kafka:5.0.1
  delegate_to: "{{ item }}"
  with_items: "{{ groups['k8s-workers'] }}"

- name: Docker Pull Zookeeper Container Images
  shell: docker pull confluentinc/cp-zookeeper:5.0.1
  delegate_to: "{{ item }}"
  with_items: "{{ groups['k8s-workers'] }}"

- name: Docker Pull Kafka-Prometheus Exporter Container Images
  shell: docker pull solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
  delegate_to: "{{ item }}"
  with_items: "{{ groups['k8s-workers'] }}"

- name: Create kubernetes namespace
  shell: kubectl create namespace congo-kafka-nonprod
  ignore_errors: true

- name: "Push Kafka charts to /tmp"
  copy: 
    src: ./templates/
    dest: /tmp/charts/

- name: Helm install Zookeeper
  shell: /usr/local/bin/helm install --name cp-zookeeper-nonprod --namespace congo-kafka-nonprod -f /tmp/charts/cp-zookeeper/values.yaml /tmp/charts/cp-zookeeper --tiller-namespace kube-tiller --namespace congo-kafka-nonprod
  ignore_errors: true

- name: Helm install Kafka Broker
  shell: /usr/local/bin/helm install --name cp-kafka-nonprod --namespace congo-kafka-nonprod -f /tmp/charts/cp-kafka/values.yaml /tmp/charts/cp-kafka --tiller-namespace kube-tiller --namespace congo-kafka-nonprod
  ignore_errors: true