- name: Copy Calico RBAC rbac-kdd.yaml manifests
  template:
    src: rbac-kdd.yaml
    dest: /tmp/rbac-kdd.yaml

- name: Create Calico RBAC Deployment
  shell: kubectl apply -f /tmp/rbac-kdd.yaml

- name: Copy calico.yaml manifests
  template:
    src: calico.yaml
    dest: /tmp/calico.yaml

- name: Create Calico Deployment
  shell: kubectl apply -f /tmp/calico.yaml

- pause:
    prompt: "Wait for containers to Pull and install"