
- name: OS patch hosts sequentially
  include_tasks: "os-patches.yml"
  with_items:
    - "{{ groups['k8s-masters'] }}"
    - "{{ groups['k8s-workers'] }}"
  when: "hostvars[host_item].inventory_hostname == inventory_hostname"
  loop_control:
      loop_var: host_item
