- name: Install docker dependencies
  become: yes
  yum:
    name: "{{item}}"
  with_items:
    - device-mapper-persistent-data
    - lvm2
  
- name: Install Docker-CE engine
  yum: 
    name: docker-ce-{{ docker_version }}
    state: installed     

- name: Create /etc/docker/ folder
  file:
    path: "/etc/docker/ "
    state: directory
    owner: "root"

- name: Configure additional engine options
  copy:
    content: "{{ docker_ce_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_ce_daemon_options is defined

- name: Create Docker HTTP Proxy config file
  blockinfile:
    path: /etc/systemd/system/docker.service.d/http_proxy.conf
    create: yes
    block: |
        [Service]
        Environment="HTTPS_PROXY=http://127.0.0.1:8888/" "NO_PROXY=localhost,127.0.0.1,10.0.0.0"

- name: restart docker
  systemd: 
    name: docker 
    state: restarted
    daemon_reload: yes
    enabled: yes