- name: Install Docker-CE engine
  yum: 
    name: docker-ce-{{ docker_version }}
    state: installed
    enablerepo: docker-ce  

- name: Create directory for trusted registry
  file:
    path: /etc/docker/certs.d/container-registry01.nonprod.domain.local
    state: directory

- name: Copy registry CA certificate
  template:
    src: container-registry01.nonprod.domain.local-ca.crt
    dest: /etc/docker/certs.d/container-registry01.nonprod.domain.local/ca.crt
    force: yes

- name: Configure additional engine options
  copy:
    content: "{{ docker_ce_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_ce_daemon_options is defined

- name: Enable docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes