    - name: Upgrade kubenetes packages
      yum:
        name: "{{ packages }}"
        enablerepo: kubernetes
      vars:
        packages:
        - kubelet-{{kubeadm_version}}
        - kubectl-{{kubeadm_version}}
        - kubeadm-{{kubeadm_version}}

    - name: Drain kubernetes worker node
      shell: kubectl drain {{ inventory_hostname_short }} --delete-local-data  --ignore-daemonsets
      register: kubeadm_drain
      delegate_to: "{{ groups['k8s-masters'][0] }}"

    - pause:
        prompt: "Wait for drain"

    - name: Upgrade worker nodes
      shell: kubeadm upgrade node config --kubelet-version {{kubernetes_version}}

    - name: Restart kubelet
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet
        enabled: yes

    - name: Uncordon worker node
      shell: kubectl uncordon {{ inventory_hostname_short }} 
      register: kubeadm_uncordon
      delegate_to: "{{ groups['k8s-masters'][0] }}"

    - pause:
        prompt: "Wait for uncordon"